# Generated by Django 2.0 on 2020-04-09 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='processos.Compra')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Despesas', to='processos.Despesas')),
            ],
            options={
                'verbose_name': 'Balanco',
                'verbose_name_plural': 'Balanco',
            },
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
