# Generated by Django 2.0 on 2020-04-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='Desconto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Desconto'),
            preserve_default=False,
        ),
    ]
