# Generated by Django 2.0 on 2020-04-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='compras_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='compras_id'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesa_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='despesa_id'),
        ),
    ]
