# Generated by Django 2.1.7 on 2020-03-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_remove_produto_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='qtd',
            new_name='quantidade',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data',
        ),
    ]
