# Generated by Django 2.1.7 on 2020-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200329_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='quantLote',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantLote'),
        ),
    ]
