# Generated by Django 2.0 on 2020-04-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_auto_20200408_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='Data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='compra',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='despesa',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
    ]
