# Generated by Django 2.0 on 2020-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_auto_20200409_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanco',
            name='compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='compra'),
        ),
        migrations.AlterField(
            model_name='balanco',
            name='despesa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='despesa'),
        ),
    ]
