# Generated by Django 2.1.7 on 2020-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_auto_20200330_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quantCompra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
