# Generated by Django 2.0 on 2020-04-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_auto_20200330_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='quantCompra',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='quantLote',
        ),
    ]
