# Generated by Django 2.0 on 2020-04-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
